package com.craiovadata.android.messenger.util

val CONVERSATIONS = "conversations"
val KEY_ROOM_ID = "key_conversation_id"
val KEY_USER_ID = "key_user_id"
val KEY_USER_PHOTO_URL = "key_user_photo_url"
val KEY_USER_NAME = "key_user_name"
val USERS = "users"
val USER_KEYWORDS = "userKeywords"
val KEYWORDS = "keywords"
val MESSAGES = "messages"
val PAL_ID = "palId"
val PAL_NAME = "palName"
val PAL_PHOTO_URL = "palPhotoUrl"
val TIMESTAMP = "timestamp"
val TOKEN = "token"
val TOKENS = "tokens"
val LAST_MESSAGE_AUTHOR = "msgAuthor"
val LAST_MESSAGE = "lastMessage"
val LAST_MESSAGE_TIME = "msgTimestamp"
val RC_SIGN_IN = 9001
val PHOTO_URL = "photoUrl"
val TEXT = "text"
val AUTHOR = "author"
val CONVERSATION_ID = "conversationID"

